// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Kf7APrnEzzkUdq3W02TdjcEmhMyBVOU',
    appId: '1:907949478310:web:ca50ae28e0d5e39078ff67',
    messagingSenderId: '907949478310',
    projectId: 'helpmeout-cbbf5',
    authDomain: 'helpmeout-cbbf5.firebaseapp.com',
    storageBucket: 'helpmeout-cbbf5.firebasestorage.app',
    measurementId: 'G-XFCCMNET4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-85H6QWLKS73H7hRkl-P3KpmTM2gbrtM',
    appId: '1:907949478310:android:f496e0a152d00f6878ff67',
    messagingSenderId: '907949478310',
    projectId: 'helpmeout-cbbf5',
    storageBucket: 'helpmeout-cbbf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-vMAfqei2xd-q1bpfVqN0BmUBibMmWJ0',
    appId: '1:907949478310:ios:0d48aee49c84d71f78ff67',
    messagingSenderId: '907949478310',
    projectId: 'helpmeout-cbbf5',
    storageBucket: 'helpmeout-cbbf5.firebasestorage.app',
    iosBundleId: 'com.example.helpmeoutFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-vMAfqei2xd-q1bpfVqN0BmUBibMmWJ0',
    appId: '1:907949478310:ios:0d48aee49c84d71f78ff67',
    messagingSenderId: '907949478310',
    projectId: 'helpmeout-cbbf5',
    storageBucket: 'helpmeout-cbbf5.firebasestorage.app',
    iosBundleId: 'com.example.helpmeoutFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Kf7APrnEzzkUdq3W02TdjcEmhMyBVOU',
    appId: '1:907949478310:web:34991d5a3a9462c178ff67',
    messagingSenderId: '907949478310',
    projectId: 'helpmeout-cbbf5',
    authDomain: 'helpmeout-cbbf5.firebaseapp.com',
    storageBucket: 'helpmeout-cbbf5.firebasestorage.app',
    measurementId: 'G-XQ0QH6MFH5',
  );
}
